We took our encoded data from other notebook and instantiated it in this notebook. The X consists of features and the Y consists of labels.

In [39]:
%store -r X
print(X)


[[18.5 19.7 22.4 ... 18.9 18.6  1. ]
 [23.7 36.3  2.2 ... 26.5 34.1  1. ]
 [18.4 27.5  0.  ... 19.7 24.4  0. ]
 ...
 [10.  20.1  0.  ... 14.3 19.   0. ]
 [ 9.9 25.3  0.  ... 14.4 24.5  0. ]
 [14.4 19.8 13.2 ... 15.4 16.6  1. ]]


In [40]:
%store -r Y
print(Y)


[1 1 1 ... 0 0 0]


In [41]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_validate

In [42]:
from sklearn.neighbors import KNeighborsClassifier

KNN Algorithm:

In [43]:
from sklearn.metrics import recall_score
from sklearn.model_selection import cross_val_predict
from sklearn.metrics import confusion_matrix

neigh = KNeighborsClassifier(n_neighbors=3)

scoring = {'accuracy': 'accuracy',
           'recall': 'recall',
           'precision': 'precision',
           'f1': 'f1'}

cv_result = cross_validate(neigh, X, Y, cv=5, scoring=scoring, return_train_score= True)

print('precision', cv_result['test_precision'])
print('recall', cv_result['test_recall'])
print('f1_score', cv_result['test_f1'])
print('Test_accuracy: ', cv_result['test_accuracy'])
print('Train_accuracy: ', cv_result['train_accuracy'])


y_pred = cross_val_predict(neigh, X, Y, cv=5)
conf_mat = confusion_matrix(Y, y_pred)
print('Confusion-Matrix')
print(conf_mat)




precision [0.6509434  0.95522388 0.74336283 0.78761062 0.82882883]
recall [0.66346154 0.61538462 0.81553398 0.86407767 0.89320388]
f1_score [0.65714286 0.74853801 0.77777778 0.82407407 0.85981308]
Test_accuracy:  [0.65217391 0.79227053 0.76811594 0.81553398 0.85436893]
Train_accuracy:  [0.93583535 0.92493947 0.92615012 0.92261185 0.91293833]
Confusion-Matrix
[[404 112]
 [119 398]]


In [ ]:
Naive Bayes Algorithm:

In [44]:
from sklearn.naive_bayes import GaussianNB

clf = GaussianNB(var_smoothing=1e-09)

scoring = {'accuracy': 'accuracy',
           'recall': 'recall',
           'precision': 'precision',
           'f1': 'f1'}

cv_result = cross_validate(clf, X, Y, cv=5, scoring=scoring, return_train_score= True)

print('precision', cv_result['test_precision'])
print('recall', cv_result['test_recall'])
print('f1_score', cv_result['test_f1'])
print('Test_accuracy: ', cv_result['test_accuracy'])
print('Train_accuracy: ', cv_result['train_accuracy'])


y_pred = cross_val_predict(clf, X, Y, cv=5)
conf_mat = confusion_matrix(Y, y_pred)
print('Confusion-Matrix')
print(conf_mat)

precision [0.71       0.83333333 0.66393443 0.84158416 0.75      ]
recall [0.68269231 0.67307692 0.78640777 0.82524272 0.87378641]
f1_score [0.69607843 0.74468085 0.72       0.83333333 0.80717489]
Test_accuracy:  [0.70048309 0.76811594 0.69565217 0.83495146 0.79126214]
Train_accuracy:  [0.81355932 0.78208232 0.78692494 0.77871826 0.77871826]
Confusion-Matrix
[[386 130]
 [120 397]]


We ran our data with the KNN algorithm and the Naive Bayes algorithm. Within the KNN algorthim, our TP and TN was greater in the confusion matrix. For the KNN algorthim, the best n_neighbours was 3. For the Naive Bayes Algorthim, the var_smoothings best values was 1e-09, the default itself was the best. The precision, recall and f1_score for both algorithms were similar.